server.port=3000

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.user=postgres.jchqbmehduhvqwwgxcej
spring.datasource.hikari.data-source-properties.password=Quizzy102006f
spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

openrouter.api.key=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