server.port=3000

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.user=postgres.jchqbmehduhvqwwgxcej
spring.datasource.hikari.data-source-properties.password=Quizzy102006f
spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

openrouter.api.key=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