server.port=3000

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.user=postgres.jchqbmehduhvqwwgxcej
spring.datasource.hikari.data-source-properties.password=Quizzy102006f
spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

openrouter.api.key=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
